
package ir.net.nicico.spl.common;


// Generated by Nicico System generator :) :D
import java.util.Enumeration;
import java.util.ResourceBundle;

/**
 *
 * @Generated by Nicico System generator :) :D 
 */
public class InitializrReaderUtility {

    static ResourceBundle rb = ResourceBundle.getBundle("config");

    public static String getResourceProperity(String key) {
        return rb.getString(key);
    }

    public static Enumeration<String> getResourceKeys() {
        return rb.getKeys();
    }

}
