package ir.net.nicico.spl.dao;

import com.aef3.data.impl.AbstractDAOImpl;
import ir.net.nicico.spl.model.Project;
import org.springframework.stereotype.Repository;


/* Generated By Nicico System Generator ( Powered by Dr.Adldoost :D ) */

@Repository
public class ProjectDao extends AbstractDAOImpl<Project, Long> {

    public ProjectDao() {
        super(Project.class);
    }
}
